name = "brine-dev"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "."
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "99b8f35602ae44869d80637281295546"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "AnalyticsDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AnalyticsDO"]

[[r2_buckets]]
binding = "R2"
bucket_name = "brine-dev"

[triggers]
crons = ["0 2 * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true

[vars]
DOMAIN_NAME = "brine.dev"
