name = "brine-dev"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "assets"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true

[vars]
DOMAIN_NAME = "brine.dev"
SITE_TITLE = "brine.dev"
SITE_DESCRIPTION = "I'm a blabby nerd that lives in the high desert..."
OWNER = "1cNgwq1reYmHBqkSvy46eFu3SkFFXTr0U_pGm8KrZns"
PODCAST_IMAGE = "https://brine.dev/images/brine_square.jpg"
PODCAST_CATEGORY = "Arts"
PODCAST_EMAIL = "ack@brine.dev"

[[d1_databases]]
binding = "DB"
database_name = "brine-dev"
database_id = "68ef6268-e99f-407d-a81a-74c08fca150e"

[[r2_buckets]]
binding = "R2"
bucket_name = "brine"

[[migrations]]
tag = "v2"
deleted_classes = ["AnalyticsDO"]

[triggers]
crons = ["*/42 * * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true